version: "3.9"

services:
  app:
    image: your-dockerhub-user/node-app:${TAG}
    container_name: node-app-prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
