name: Build, Push, and Deploy (DEV)

on:
  push:
    branches:
    - dev
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set dynamic Docker tag
    - name: Set Docker tag
      run: echo "TAG=build-${{ github.run_number }}" >> $GITHUB_ENV

    # 3. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/Dynamic-dev:latest
          ${{ secrets.DOCKER_USERNAME }}/Dynamic-dev:${{ env.TAG }}

    # 5. SSH to EC2 and deploy using docker-compose
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home 
          TAG=${{ env.TAG }} docker compose pull
          TAG=${{ env.TAG }} docker compose up -d
