name: Build, Push, and Deploy (Dev)

on:
  push:
    branches:
    - dev
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Docker tag (Dev)
      run: echo "TAG=dev-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image (Dev)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/dynamic-dev:latest
          ${{ secrets.DOCKER_USERNAME }}/dynamic-dev:${{ env.TAG }}

    - name: Deploy to EC2 (Dev)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST_DEV }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY_DEV }}
        script: |
          cd /home/ubuntu/ahmed/rakaya-dev
          TAG=${{ env.TAG }} docker compose -f docker-compose.dev.yml pull
          TAG=${{ env.TAG }} docker compose -f docker-compose.dev.yml up -d
